/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsuariosAcessosRouteImport } from './routes/_authenticated/usuarios-acessos'
import { Route as AuthenticatedTarefasRouteImport } from './routes/_authenticated/tarefas'
import { Route as AuthenticatedScriptsRouteImport } from './routes/_authenticated/scripts'
import { Route as AuthenticatedResgatesRouteImport } from './routes/_authenticated/resgates'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedProcessosComerciaisRouteImport } from './routes/_authenticated/processos-comerciais'
import { Route as AuthenticatedPlacarHallDaFamaRouteImport } from './routes/_authenticated/placar-hall-da-fama'
import { Route as AuthenticatedPlacarDiarioRouteImport } from './routes/_authenticated/placar-diario'
import { Route as AuthenticatedPerdidosRouteImport } from './routes/_authenticated/perdidos'
import { Route as AuthenticatedPainelAdmRouteImport } from './routes/_authenticated/painel-adm'
import { Route as AuthenticatedMinhaComissaoRouteImport } from './routes/_authenticated/minha-comissao'
import { Route as AuthenticatedMeusFeedbacksRouteImport } from './routes/_authenticated/meus-feedbacks'
import { Route as AuthenticatedMeuPerfilRouteImport } from './routes/_authenticated/meu-perfil'
import { Route as AuthenticatedMetasMatriculaRouteImport } from './routes/_authenticated/metas-matricula'
import { Route as AuthenticatedMateriaisRouteImport } from './routes/_authenticated/materiais'
import { Route as AuthenticatedLinksBolsistaRouteImport } from './routes/_authenticated/links-bolsista'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedIntegracaoArenaRouteImport } from './routes/_authenticated/integracao-arena'
import { Route as AuthenticatedImportarRouteImport } from './routes/_authenticated/importar'
import { Route as AuthenticatedHojeRouteImport } from './routes/_authenticated/hoje'
import { Route as AuthenticatedFunilRouteImport } from './routes/_authenticated/funil'
import { Route as AuthenticatedFilaRouteImport } from './routes/_authenticated/fila'
import { Route as AuthenticatedFeedbackIndividualRouteImport } from './routes/_authenticated/feedback-individual'
import { Route as AuthenticatedEquipesRouteImport } from './routes/_authenticated/equipes'
import { Route as AuthenticatedDiscadorRouteImport } from './routes/_authenticated/discador'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedComissaoVendedoresRouteImport } from './routes/_authenticated/comissao-vendedores'
import { Route as AuthenticatedComissaoLiderancaRouteImport } from './routes/_authenticated/comissao-lideranca'
import { Route as AuthenticatedCheckoutDoDiaRouteImport } from './routes/_authenticated/checkout-do-dia'
import { Route as AuthenticatedAssistentesIaRouteImport } from './routes/_authenticated/assistentes-ia'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as ApiPublicReceiveScholarshipLeadRouteImport } from './routes/api/public/receive-scholarship-lead'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsuariosAcessosRoute =
  AuthenticatedUsuariosAcessosRouteImport.update({
    id: '/usuarios-acessos',
    path: '/usuarios-acessos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTarefasRoute = AuthenticatedTarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScriptsRoute = AuthenticatedScriptsRouteImport.update({
  id: '/scripts',
  path: '/scripts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResgatesRoute = AuthenticatedResgatesRouteImport.update({
  id: '/resgates',
  path: '/resgates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProcessosComerciaisRoute =
  AuthenticatedProcessosComerciaisRouteImport.update({
    id: '/processos-comerciais',
    path: '/processos-comerciais',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlacarHallDaFamaRoute =
  AuthenticatedPlacarHallDaFamaRouteImport.update({
    id: '/placar-hall-da-fama',
    path: '/placar-hall-da-fama',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlacarDiarioRoute =
  AuthenticatedPlacarDiarioRouteImport.update({
    id: '/placar-diario',
    path: '/placar-diario',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPerdidosRoute = AuthenticatedPerdidosRouteImport.update({
  id: '/perdidos',
  path: '/perdidos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelAdmRoute = AuthenticatedPainelAdmRouteImport.update({
  id: '/painel-adm',
  path: '/painel-adm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMinhaComissaoRoute =
  AuthenticatedMinhaComissaoRouteImport.update({
    id: '/minha-comissao',
    path: '/minha-comissao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMeusFeedbacksRoute =
  AuthenticatedMeusFeedbacksRouteImport.update({
    id: '/meus-feedbacks',
    path: '/meus-feedbacks',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMeuPerfilRoute = AuthenticatedMeuPerfilRouteImport.update({
  id: '/meu-perfil',
  path: '/meu-perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMetasMatriculaRoute =
  AuthenticatedMetasMatriculaRouteImport.update({
    id: '/metas-matricula',
    path: '/metas-matricula',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMateriaisRoute = AuthenticatedMateriaisRouteImport.update({
  id: '/materiais',
  path: '/materiais',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLinksBolsistaRoute =
  AuthenticatedLinksBolsistaRouteImport.update({
    id: '/links-bolsista',
    path: '/links-bolsista',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntegracaoArenaRoute =
  AuthenticatedIntegracaoArenaRouteImport.update({
    id: '/integracao-arena',
    path: '/integracao-arena',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedImportarRoute = AuthenticatedImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHojeRoute = AuthenticatedHojeRouteImport.update({
  id: '/hoje',
  path: '/hoje',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFunilRoute = AuthenticatedFunilRouteImport.update({
  id: '/funil',
  path: '/funil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFilaRoute = AuthenticatedFilaRouteImport.update({
  id: '/fila',
  path: '/fila',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeedbackIndividualRoute =
  AuthenticatedFeedbackIndividualRouteImport.update({
    id: '/feedback-individual',
    path: '/feedback-individual',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEquipesRoute = AuthenticatedEquipesRouteImport.update({
  id: '/equipes',
  path: '/equipes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiscadorRoute = AuthenticatedDiscadorRouteImport.update({
  id: '/discador',
  path: '/discador',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComissaoVendedoresRoute =
  AuthenticatedComissaoVendedoresRouteImport.update({
    id: '/comissao-vendedores',
    path: '/comissao-vendedores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComissaoLiderancaRoute =
  AuthenticatedComissaoLiderancaRouteImport.update({
    id: '/comissao-lideranca',
    path: '/comissao-lideranca',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCheckoutDoDiaRoute =
  AuthenticatedCheckoutDoDiaRouteImport.update({
    id: '/checkout-do-dia',
    path: '/checkout-do-dia',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssistentesIaRoute =
  AuthenticatedAssistentesIaRouteImport.update({
    id: '/assistentes-ia',
    path: '/assistentes-ia',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicReceiveScholarshipLeadRoute =
  ApiPublicReceiveScholarshipLeadRouteImport.update({
    id: '/api/public/receive-scholarship-lead',
    path: '/api/public/receive-scholarship-lead',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/assistentes-ia': typeof AuthenticatedAssistentesIaRoute
  '/checkout-do-dia': typeof AuthenticatedCheckoutDoDiaRoute
  '/comissao-lideranca': typeof AuthenticatedComissaoLiderancaRoute
  '/comissao-vendedores': typeof AuthenticatedComissaoVendedoresRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/discador': typeof AuthenticatedDiscadorRoute
  '/equipes': typeof AuthenticatedEquipesRoute
  '/feedback-individual': typeof AuthenticatedFeedbackIndividualRoute
  '/fila': typeof AuthenticatedFilaRoute
  '/funil': typeof AuthenticatedFunilRoute
  '/hoje': typeof AuthenticatedHojeRoute
  '/importar': typeof AuthenticatedImportarRoute
  '/integracao-arena': typeof AuthenticatedIntegracaoArenaRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/links-bolsista': typeof AuthenticatedLinksBolsistaRoute
  '/materiais': typeof AuthenticatedMateriaisRoute
  '/metas-matricula': typeof AuthenticatedMetasMatriculaRoute
  '/meu-perfil': typeof AuthenticatedMeuPerfilRoute
  '/meus-feedbacks': typeof AuthenticatedMeusFeedbacksRoute
  '/minha-comissao': typeof AuthenticatedMinhaComissaoRoute
  '/painel-adm': typeof AuthenticatedPainelAdmRoute
  '/perdidos': typeof AuthenticatedPerdidosRoute
  '/placar-diario': typeof AuthenticatedPlacarDiarioRoute
  '/placar-hall-da-fama': typeof AuthenticatedPlacarHallDaFamaRoute
  '/processos-comerciais': typeof AuthenticatedProcessosComerciaisRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/resgates': typeof AuthenticatedResgatesRoute
  '/scripts': typeof AuthenticatedScriptsRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
  '/usuarios-acessos': typeof AuthenticatedUsuariosAcessosRoute
  '/api/public/receive-scholarship-lead': typeof ApiPublicReceiveScholarshipLeadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/assistentes-ia': typeof AuthenticatedAssistentesIaRoute
  '/checkout-do-dia': typeof AuthenticatedCheckoutDoDiaRoute
  '/comissao-lideranca': typeof AuthenticatedComissaoLiderancaRoute
  '/comissao-vendedores': typeof AuthenticatedComissaoVendedoresRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/discador': typeof AuthenticatedDiscadorRoute
  '/equipes': typeof AuthenticatedEquipesRoute
  '/feedback-individual': typeof AuthenticatedFeedbackIndividualRoute
  '/fila': typeof AuthenticatedFilaRoute
  '/funil': typeof AuthenticatedFunilRoute
  '/hoje': typeof AuthenticatedHojeRoute
  '/importar': typeof AuthenticatedImportarRoute
  '/integracao-arena': typeof AuthenticatedIntegracaoArenaRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/links-bolsista': typeof AuthenticatedLinksBolsistaRoute
  '/materiais': typeof AuthenticatedMateriaisRoute
  '/metas-matricula': typeof AuthenticatedMetasMatriculaRoute
  '/meu-perfil': typeof AuthenticatedMeuPerfilRoute
  '/meus-feedbacks': typeof AuthenticatedMeusFeedbacksRoute
  '/minha-comissao': typeof AuthenticatedMinhaComissaoRoute
  '/painel-adm': typeof AuthenticatedPainelAdmRoute
  '/perdidos': typeof AuthenticatedPerdidosRoute
  '/placar-diario': typeof AuthenticatedPlacarDiarioRoute
  '/placar-hall-da-fama': typeof AuthenticatedPlacarHallDaFamaRoute
  '/processos-comerciais': typeof AuthenticatedProcessosComerciaisRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/resgates': typeof AuthenticatedResgatesRoute
  '/scripts': typeof AuthenticatedScriptsRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
  '/usuarios-acessos': typeof AuthenticatedUsuariosAcessosRoute
  '/api/public/receive-scholarship-lead': typeof ApiPublicReceiveScholarshipLeadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/assistentes-ia': typeof AuthenticatedAssistentesIaRoute
  '/_authenticated/checkout-do-dia': typeof AuthenticatedCheckoutDoDiaRoute
  '/_authenticated/comissao-lideranca': typeof AuthenticatedComissaoLiderancaRoute
  '/_authenticated/comissao-vendedores': typeof AuthenticatedComissaoVendedoresRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/discador': typeof AuthenticatedDiscadorRoute
  '/_authenticated/equipes': typeof AuthenticatedEquipesRoute
  '/_authenticated/feedback-individual': typeof AuthenticatedFeedbackIndividualRoute
  '/_authenticated/fila': typeof AuthenticatedFilaRoute
  '/_authenticated/funil': typeof AuthenticatedFunilRoute
  '/_authenticated/hoje': typeof AuthenticatedHojeRoute
  '/_authenticated/importar': typeof AuthenticatedImportarRoute
  '/_authenticated/integracao-arena': typeof AuthenticatedIntegracaoArenaRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/links-bolsista': typeof AuthenticatedLinksBolsistaRoute
  '/_authenticated/materiais': typeof AuthenticatedMateriaisRoute
  '/_authenticated/metas-matricula': typeof AuthenticatedMetasMatriculaRoute
  '/_authenticated/meu-perfil': typeof AuthenticatedMeuPerfilRoute
  '/_authenticated/meus-feedbacks': typeof AuthenticatedMeusFeedbacksRoute
  '/_authenticated/minha-comissao': typeof AuthenticatedMinhaComissaoRoute
  '/_authenticated/painel-adm': typeof AuthenticatedPainelAdmRoute
  '/_authenticated/perdidos': typeof AuthenticatedPerdidosRoute
  '/_authenticated/placar-diario': typeof AuthenticatedPlacarDiarioRoute
  '/_authenticated/placar-hall-da-fama': typeof AuthenticatedPlacarHallDaFamaRoute
  '/_authenticated/processos-comerciais': typeof AuthenticatedProcessosComerciaisRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/resgates': typeof AuthenticatedResgatesRoute
  '/_authenticated/scripts': typeof AuthenticatedScriptsRoute
  '/_authenticated/tarefas': typeof AuthenticatedTarefasRoute
  '/_authenticated/usuarios-acessos': typeof AuthenticatedUsuariosAcessosRoute
  '/api/public/receive-scholarship-lead': typeof ApiPublicReceiveScholarshipLeadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/agenda'
    | '/assistentes-ia'
    | '/checkout-do-dia'
    | '/comissao-lideranca'
    | '/comissao-vendedores'
    | '/configuracoes'
    | '/dashboard'
    | '/discador'
    | '/equipes'
    | '/feedback-individual'
    | '/fila'
    | '/funil'
    | '/hoje'
    | '/importar'
    | '/integracao-arena'
    | '/leads'
    | '/links-bolsista'
    | '/materiais'
    | '/metas-matricula'
    | '/meu-perfil'
    | '/meus-feedbacks'
    | '/minha-comissao'
    | '/painel-adm'
    | '/perdidos'
    | '/placar-diario'
    | '/placar-hall-da-fama'
    | '/processos-comerciais'
    | '/relatorios'
    | '/resgates'
    | '/scripts'
    | '/tarefas'
    | '/usuarios-acessos'
    | '/api/public/receive-scholarship-lead'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/agenda'
    | '/assistentes-ia'
    | '/checkout-do-dia'
    | '/comissao-lideranca'
    | '/comissao-vendedores'
    | '/configuracoes'
    | '/dashboard'
    | '/discador'
    | '/equipes'
    | '/feedback-individual'
    | '/fila'
    | '/funil'
    | '/hoje'
    | '/importar'
    | '/integracao-arena'
    | '/leads'
    | '/links-bolsista'
    | '/materiais'
    | '/metas-matricula'
    | '/meu-perfil'
    | '/meus-feedbacks'
    | '/minha-comissao'
    | '/painel-adm'
    | '/perdidos'
    | '/placar-diario'
    | '/placar-hall-da-fama'
    | '/processos-comerciais'
    | '/relatorios'
    | '/resgates'
    | '/scripts'
    | '/tarefas'
    | '/usuarios-acessos'
    | '/api/public/receive-scholarship-lead'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/agenda'
    | '/_authenticated/assistentes-ia'
    | '/_authenticated/checkout-do-dia'
    | '/_authenticated/comissao-lideranca'
    | '/_authenticated/comissao-vendedores'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/discador'
    | '/_authenticated/equipes'
    | '/_authenticated/feedback-individual'
    | '/_authenticated/fila'
    | '/_authenticated/funil'
    | '/_authenticated/hoje'
    | '/_authenticated/importar'
    | '/_authenticated/integracao-arena'
    | '/_authenticated/leads'
    | '/_authenticated/links-bolsista'
    | '/_authenticated/materiais'
    | '/_authenticated/metas-matricula'
    | '/_authenticated/meu-perfil'
    | '/_authenticated/meus-feedbacks'
    | '/_authenticated/minha-comissao'
    | '/_authenticated/painel-adm'
    | '/_authenticated/perdidos'
    | '/_authenticated/placar-diario'
    | '/_authenticated/placar-hall-da-fama'
    | '/_authenticated/processos-comerciais'
    | '/_authenticated/relatorios'
    | '/_authenticated/resgates'
    | '/_authenticated/scripts'
    | '/_authenticated/tarefas'
    | '/_authenticated/usuarios-acessos'
    | '/api/public/receive-scholarship-lead'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicReceiveScholarshipLeadRoute: typeof ApiPublicReceiveScholarshipLeadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/usuarios-acessos': {
      id: '/_authenticated/usuarios-acessos'
      path: '/usuarios-acessos'
      fullPath: '/usuarios-acessos'
      preLoaderRoute: typeof AuthenticatedUsuariosAcessosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tarefas': {
      id: '/_authenticated/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof AuthenticatedTarefasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scripts': {
      id: '/_authenticated/scripts'
      path: '/scripts'
      fullPath: '/scripts'
      preLoaderRoute: typeof AuthenticatedScriptsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resgates': {
      id: '/_authenticated/resgates'
      path: '/resgates'
      fullPath: '/resgates'
      preLoaderRoute: typeof AuthenticatedResgatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/processos-comerciais': {
      id: '/_authenticated/processos-comerciais'
      path: '/processos-comerciais'
      fullPath: '/processos-comerciais'
      preLoaderRoute: typeof AuthenticatedProcessosComerciaisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/placar-hall-da-fama': {
      id: '/_authenticated/placar-hall-da-fama'
      path: '/placar-hall-da-fama'
      fullPath: '/placar-hall-da-fama'
      preLoaderRoute: typeof AuthenticatedPlacarHallDaFamaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/placar-diario': {
      id: '/_authenticated/placar-diario'
      path: '/placar-diario'
      fullPath: '/placar-diario'
      preLoaderRoute: typeof AuthenticatedPlacarDiarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perdidos': {
      id: '/_authenticated/perdidos'
      path: '/perdidos'
      fullPath: '/perdidos'
      preLoaderRoute: typeof AuthenticatedPerdidosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel-adm': {
      id: '/_authenticated/painel-adm'
      path: '/painel-adm'
      fullPath: '/painel-adm'
      preLoaderRoute: typeof AuthenticatedPainelAdmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/minha-comissao': {
      id: '/_authenticated/minha-comissao'
      path: '/minha-comissao'
      fullPath: '/minha-comissao'
      preLoaderRoute: typeof AuthenticatedMinhaComissaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meus-feedbacks': {
      id: '/_authenticated/meus-feedbacks'
      path: '/meus-feedbacks'
      fullPath: '/meus-feedbacks'
      preLoaderRoute: typeof AuthenticatedMeusFeedbacksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meu-perfil': {
      id: '/_authenticated/meu-perfil'
      path: '/meu-perfil'
      fullPath: '/meu-perfil'
      preLoaderRoute: typeof AuthenticatedMeuPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/metas-matricula': {
      id: '/_authenticated/metas-matricula'
      path: '/metas-matricula'
      fullPath: '/metas-matricula'
      preLoaderRoute: typeof AuthenticatedMetasMatriculaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/materiais': {
      id: '/_authenticated/materiais'
      path: '/materiais'
      fullPath: '/materiais'
      preLoaderRoute: typeof AuthenticatedMateriaisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/links-bolsista': {
      id: '/_authenticated/links-bolsista'
      path: '/links-bolsista'
      fullPath: '/links-bolsista'
      preLoaderRoute: typeof AuthenticatedLinksBolsistaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integracao-arena': {
      id: '/_authenticated/integracao-arena'
      path: '/integracao-arena'
      fullPath: '/integracao-arena'
      preLoaderRoute: typeof AuthenticatedIntegracaoArenaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/importar': {
      id: '/_authenticated/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof AuthenticatedImportarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hoje': {
      id: '/_authenticated/hoje'
      path: '/hoje'
      fullPath: '/hoje'
      preLoaderRoute: typeof AuthenticatedHojeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/funil': {
      id: '/_authenticated/funil'
      path: '/funil'
      fullPath: '/funil'
      preLoaderRoute: typeof AuthenticatedFunilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fila': {
      id: '/_authenticated/fila'
      path: '/fila'
      fullPath: '/fila'
      preLoaderRoute: typeof AuthenticatedFilaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feedback-individual': {
      id: '/_authenticated/feedback-individual'
      path: '/feedback-individual'
      fullPath: '/feedback-individual'
      preLoaderRoute: typeof AuthenticatedFeedbackIndividualRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipes': {
      id: '/_authenticated/equipes'
      path: '/equipes'
      fullPath: '/equipes'
      preLoaderRoute: typeof AuthenticatedEquipesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/discador': {
      id: '/_authenticated/discador'
      path: '/discador'
      fullPath: '/discador'
      preLoaderRoute: typeof AuthenticatedDiscadorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comissao-vendedores': {
      id: '/_authenticated/comissao-vendedores'
      path: '/comissao-vendedores'
      fullPath: '/comissao-vendedores'
      preLoaderRoute: typeof AuthenticatedComissaoVendedoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comissao-lideranca': {
      id: '/_authenticated/comissao-lideranca'
      path: '/comissao-lideranca'
      fullPath: '/comissao-lideranca'
      preLoaderRoute: typeof AuthenticatedComissaoLiderancaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkout-do-dia': {
      id: '/_authenticated/checkout-do-dia'
      path: '/checkout-do-dia'
      fullPath: '/checkout-do-dia'
      preLoaderRoute: typeof AuthenticatedCheckoutDoDiaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistentes-ia': {
      id: '/_authenticated/assistentes-ia'
      path: '/assistentes-ia'
      fullPath: '/assistentes-ia'
      preLoaderRoute: typeof AuthenticatedAssistentesIaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/receive-scholarship-lead': {
      id: '/api/public/receive-scholarship-lead'
      path: '/api/public/receive-scholarship-lead'
      fullPath: '/api/public/receive-scholarship-lead'
      preLoaderRoute: typeof ApiPublicReceiveScholarshipLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedAssistentesIaRoute: typeof AuthenticatedAssistentesIaRoute
  AuthenticatedCheckoutDoDiaRoute: typeof AuthenticatedCheckoutDoDiaRoute
  AuthenticatedComissaoLiderancaRoute: typeof AuthenticatedComissaoLiderancaRoute
  AuthenticatedComissaoVendedoresRoute: typeof AuthenticatedComissaoVendedoresRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDiscadorRoute: typeof AuthenticatedDiscadorRoute
  AuthenticatedEquipesRoute: typeof AuthenticatedEquipesRoute
  AuthenticatedFeedbackIndividualRoute: typeof AuthenticatedFeedbackIndividualRoute
  AuthenticatedFilaRoute: typeof AuthenticatedFilaRoute
  AuthenticatedFunilRoute: typeof AuthenticatedFunilRoute
  AuthenticatedHojeRoute: typeof AuthenticatedHojeRoute
  AuthenticatedImportarRoute: typeof AuthenticatedImportarRoute
  AuthenticatedIntegracaoArenaRoute: typeof AuthenticatedIntegracaoArenaRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedLinksBolsistaRoute: typeof AuthenticatedLinksBolsistaRoute
  AuthenticatedMateriaisRoute: typeof AuthenticatedMateriaisRoute
  AuthenticatedMetasMatriculaRoute: typeof AuthenticatedMetasMatriculaRoute
  AuthenticatedMeuPerfilRoute: typeof AuthenticatedMeuPerfilRoute
  AuthenticatedMeusFeedbacksRoute: typeof AuthenticatedMeusFeedbacksRoute
  AuthenticatedMinhaComissaoRoute: typeof AuthenticatedMinhaComissaoRoute
  AuthenticatedPainelAdmRoute: typeof AuthenticatedPainelAdmRoute
  AuthenticatedPerdidosRoute: typeof AuthenticatedPerdidosRoute
  AuthenticatedPlacarDiarioRoute: typeof AuthenticatedPlacarDiarioRoute
  AuthenticatedPlacarHallDaFamaRoute: typeof AuthenticatedPlacarHallDaFamaRoute
  AuthenticatedProcessosComerciaisRoute: typeof AuthenticatedProcessosComerciaisRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedResgatesRoute: typeof AuthenticatedResgatesRoute
  AuthenticatedScriptsRoute: typeof AuthenticatedScriptsRoute
  AuthenticatedTarefasRoute: typeof AuthenticatedTarefasRoute
  AuthenticatedUsuariosAcessosRoute: typeof AuthenticatedUsuariosAcessosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedAssistentesIaRoute: AuthenticatedAssistentesIaRoute,
  AuthenticatedCheckoutDoDiaRoute: AuthenticatedCheckoutDoDiaRoute,
  AuthenticatedComissaoLiderancaRoute: AuthenticatedComissaoLiderancaRoute,
  AuthenticatedComissaoVendedoresRoute: AuthenticatedComissaoVendedoresRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDiscadorRoute: AuthenticatedDiscadorRoute,
  AuthenticatedEquipesRoute: AuthenticatedEquipesRoute,
  AuthenticatedFeedbackIndividualRoute: AuthenticatedFeedbackIndividualRoute,
  AuthenticatedFilaRoute: AuthenticatedFilaRoute,
  AuthenticatedFunilRoute: AuthenticatedFunilRoute,
  AuthenticatedHojeRoute: AuthenticatedHojeRoute,
  AuthenticatedImportarRoute: AuthenticatedImportarRoute,
  AuthenticatedIntegracaoArenaRoute: AuthenticatedIntegracaoArenaRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedLinksBolsistaRoute: AuthenticatedLinksBolsistaRoute,
  AuthenticatedMateriaisRoute: AuthenticatedMateriaisRoute,
  AuthenticatedMetasMatriculaRoute: AuthenticatedMetasMatriculaRoute,
  AuthenticatedMeuPerfilRoute: AuthenticatedMeuPerfilRoute,
  AuthenticatedMeusFeedbacksRoute: AuthenticatedMeusFeedbacksRoute,
  AuthenticatedMinhaComissaoRoute: AuthenticatedMinhaComissaoRoute,
  AuthenticatedPainelAdmRoute: AuthenticatedPainelAdmRoute,
  AuthenticatedPerdidosRoute: AuthenticatedPerdidosRoute,
  AuthenticatedPlacarDiarioRoute: AuthenticatedPlacarDiarioRoute,
  AuthenticatedPlacarHallDaFamaRoute: AuthenticatedPlacarHallDaFamaRoute,
  AuthenticatedProcessosComerciaisRoute: AuthenticatedProcessosComerciaisRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedResgatesRoute: AuthenticatedResgatesRoute,
  AuthenticatedScriptsRoute: AuthenticatedScriptsRoute,
  AuthenticatedTarefasRoute: AuthenticatedTarefasRoute,
  AuthenticatedUsuariosAcessosRoute: AuthenticatedUsuariosAcessosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicReceiveScholarshipLeadRoute: ApiPublicReceiveScholarshipLeadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
