/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTarefasRouteImport } from './routes/_authenticated/tarefas'
import { Route as AuthenticatedResgatesRouteImport } from './routes/_authenticated/resgates'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedProcessosComerciaisRouteImport } from './routes/_authenticated/processos-comerciais'
import { Route as AuthenticatedPlacarDiarioRouteImport } from './routes/_authenticated/placar-diario'
import { Route as AuthenticatedPerdidosRouteImport } from './routes/_authenticated/perdidos'
import { Route as AuthenticatedPainelAdmRouteImport } from './routes/_authenticated/painel-adm'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedIntegracaoArenaRouteImport } from './routes/_authenticated/integracao-arena'
import { Route as AuthenticatedImportarRouteImport } from './routes/_authenticated/importar'
import { Route as AuthenticatedHojeRouteImport } from './routes/_authenticated/hoje'
import { Route as AuthenticatedFunilRouteImport } from './routes/_authenticated/funil'
import { Route as AuthenticatedFilaRouteImport } from './routes/_authenticated/fila'
import { Route as AuthenticatedDiscadorRouteImport } from './routes/_authenticated/discador'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedCheckoutDoDiaRouteImport } from './routes/_authenticated/checkout-do-dia'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTarefasRoute = AuthenticatedTarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResgatesRoute = AuthenticatedResgatesRouteImport.update({
  id: '/resgates',
  path: '/resgates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProcessosComerciaisRoute =
  AuthenticatedProcessosComerciaisRouteImport.update({
    id: '/processos-comerciais',
    path: '/processos-comerciais',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlacarDiarioRoute =
  AuthenticatedPlacarDiarioRouteImport.update({
    id: '/placar-diario',
    path: '/placar-diario',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPerdidosRoute = AuthenticatedPerdidosRouteImport.update({
  id: '/perdidos',
  path: '/perdidos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelAdmRoute = AuthenticatedPainelAdmRouteImport.update({
  id: '/painel-adm',
  path: '/painel-adm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntegracaoArenaRoute =
  AuthenticatedIntegracaoArenaRouteImport.update({
    id: '/integracao-arena',
    path: '/integracao-arena',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedImportarRoute = AuthenticatedImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHojeRoute = AuthenticatedHojeRouteImport.update({
  id: '/hoje',
  path: '/hoje',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFunilRoute = AuthenticatedFunilRouteImport.update({
  id: '/funil',
  path: '/funil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFilaRoute = AuthenticatedFilaRouteImport.update({
  id: '/fila',
  path: '/fila',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiscadorRoute = AuthenticatedDiscadorRouteImport.update({
  id: '/discador',
  path: '/discador',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCheckoutDoDiaRoute =
  AuthenticatedCheckoutDoDiaRouteImport.update({
    id: '/checkout-do-dia',
    path: '/checkout-do-dia',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/checkout-do-dia': typeof AuthenticatedCheckoutDoDiaRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/discador': typeof AuthenticatedDiscadorRoute
  '/fila': typeof AuthenticatedFilaRoute
  '/funil': typeof AuthenticatedFunilRoute
  '/hoje': typeof AuthenticatedHojeRoute
  '/importar': typeof AuthenticatedImportarRoute
  '/integracao-arena': typeof AuthenticatedIntegracaoArenaRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/painel-adm': typeof AuthenticatedPainelAdmRoute
  '/perdidos': typeof AuthenticatedPerdidosRoute
  '/placar-diario': typeof AuthenticatedPlacarDiarioRoute
  '/processos-comerciais': typeof AuthenticatedProcessosComerciaisRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/resgates': typeof AuthenticatedResgatesRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/checkout-do-dia': typeof AuthenticatedCheckoutDoDiaRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/discador': typeof AuthenticatedDiscadorRoute
  '/fila': typeof AuthenticatedFilaRoute
  '/funil': typeof AuthenticatedFunilRoute
  '/hoje': typeof AuthenticatedHojeRoute
  '/importar': typeof AuthenticatedImportarRoute
  '/integracao-arena': typeof AuthenticatedIntegracaoArenaRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/painel-adm': typeof AuthenticatedPainelAdmRoute
  '/perdidos': typeof AuthenticatedPerdidosRoute
  '/placar-diario': typeof AuthenticatedPlacarDiarioRoute
  '/processos-comerciais': typeof AuthenticatedProcessosComerciaisRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/resgates': typeof AuthenticatedResgatesRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/checkout-do-dia': typeof AuthenticatedCheckoutDoDiaRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/discador': typeof AuthenticatedDiscadorRoute
  '/_authenticated/fila': typeof AuthenticatedFilaRoute
  '/_authenticated/funil': typeof AuthenticatedFunilRoute
  '/_authenticated/hoje': typeof AuthenticatedHojeRoute
  '/_authenticated/importar': typeof AuthenticatedImportarRoute
  '/_authenticated/integracao-arena': typeof AuthenticatedIntegracaoArenaRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/painel-adm': typeof AuthenticatedPainelAdmRoute
  '/_authenticated/perdidos': typeof AuthenticatedPerdidosRoute
  '/_authenticated/placar-diario': typeof AuthenticatedPlacarDiarioRoute
  '/_authenticated/processos-comerciais': typeof AuthenticatedProcessosComerciaisRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/resgates': typeof AuthenticatedResgatesRoute
  '/_authenticated/tarefas': typeof AuthenticatedTarefasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/agenda'
    | '/checkout-do-dia'
    | '/configuracoes'
    | '/dashboard'
    | '/discador'
    | '/fila'
    | '/funil'
    | '/hoje'
    | '/importar'
    | '/integracao-arena'
    | '/leads'
    | '/painel-adm'
    | '/perdidos'
    | '/placar-diario'
    | '/processos-comerciais'
    | '/relatorios'
    | '/resgates'
    | '/tarefas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/agenda'
    | '/checkout-do-dia'
    | '/configuracoes'
    | '/dashboard'
    | '/discador'
    | '/fila'
    | '/funil'
    | '/hoje'
    | '/importar'
    | '/integracao-arena'
    | '/leads'
    | '/painel-adm'
    | '/perdidos'
    | '/placar-diario'
    | '/processos-comerciais'
    | '/relatorios'
    | '/resgates'
    | '/tarefas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/agenda'
    | '/_authenticated/checkout-do-dia'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/discador'
    | '/_authenticated/fila'
    | '/_authenticated/funil'
    | '/_authenticated/hoje'
    | '/_authenticated/importar'
    | '/_authenticated/integracao-arena'
    | '/_authenticated/leads'
    | '/_authenticated/painel-adm'
    | '/_authenticated/perdidos'
    | '/_authenticated/placar-diario'
    | '/_authenticated/processos-comerciais'
    | '/_authenticated/relatorios'
    | '/_authenticated/resgates'
    | '/_authenticated/tarefas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tarefas': {
      id: '/_authenticated/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof AuthenticatedTarefasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resgates': {
      id: '/_authenticated/resgates'
      path: '/resgates'
      fullPath: '/resgates'
      preLoaderRoute: typeof AuthenticatedResgatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/processos-comerciais': {
      id: '/_authenticated/processos-comerciais'
      path: '/processos-comerciais'
      fullPath: '/processos-comerciais'
      preLoaderRoute: typeof AuthenticatedProcessosComerciaisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/placar-diario': {
      id: '/_authenticated/placar-diario'
      path: '/placar-diario'
      fullPath: '/placar-diario'
      preLoaderRoute: typeof AuthenticatedPlacarDiarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perdidos': {
      id: '/_authenticated/perdidos'
      path: '/perdidos'
      fullPath: '/perdidos'
      preLoaderRoute: typeof AuthenticatedPerdidosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel-adm': {
      id: '/_authenticated/painel-adm'
      path: '/painel-adm'
      fullPath: '/painel-adm'
      preLoaderRoute: typeof AuthenticatedPainelAdmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integracao-arena': {
      id: '/_authenticated/integracao-arena'
      path: '/integracao-arena'
      fullPath: '/integracao-arena'
      preLoaderRoute: typeof AuthenticatedIntegracaoArenaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/importar': {
      id: '/_authenticated/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof AuthenticatedImportarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hoje': {
      id: '/_authenticated/hoje'
      path: '/hoje'
      fullPath: '/hoje'
      preLoaderRoute: typeof AuthenticatedHojeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/funil': {
      id: '/_authenticated/funil'
      path: '/funil'
      fullPath: '/funil'
      preLoaderRoute: typeof AuthenticatedFunilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fila': {
      id: '/_authenticated/fila'
      path: '/fila'
      fullPath: '/fila'
      preLoaderRoute: typeof AuthenticatedFilaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/discador': {
      id: '/_authenticated/discador'
      path: '/discador'
      fullPath: '/discador'
      preLoaderRoute: typeof AuthenticatedDiscadorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkout-do-dia': {
      id: '/_authenticated/checkout-do-dia'
      path: '/checkout-do-dia'
      fullPath: '/checkout-do-dia'
      preLoaderRoute: typeof AuthenticatedCheckoutDoDiaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedCheckoutDoDiaRoute: typeof AuthenticatedCheckoutDoDiaRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDiscadorRoute: typeof AuthenticatedDiscadorRoute
  AuthenticatedFilaRoute: typeof AuthenticatedFilaRoute
  AuthenticatedFunilRoute: typeof AuthenticatedFunilRoute
  AuthenticatedHojeRoute: typeof AuthenticatedHojeRoute
  AuthenticatedImportarRoute: typeof AuthenticatedImportarRoute
  AuthenticatedIntegracaoArenaRoute: typeof AuthenticatedIntegracaoArenaRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedPainelAdmRoute: typeof AuthenticatedPainelAdmRoute
  AuthenticatedPerdidosRoute: typeof AuthenticatedPerdidosRoute
  AuthenticatedPlacarDiarioRoute: typeof AuthenticatedPlacarDiarioRoute
  AuthenticatedProcessosComerciaisRoute: typeof AuthenticatedProcessosComerciaisRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedResgatesRoute: typeof AuthenticatedResgatesRoute
  AuthenticatedTarefasRoute: typeof AuthenticatedTarefasRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedCheckoutDoDiaRoute: AuthenticatedCheckoutDoDiaRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDiscadorRoute: AuthenticatedDiscadorRoute,
  AuthenticatedFilaRoute: AuthenticatedFilaRoute,
  AuthenticatedFunilRoute: AuthenticatedFunilRoute,
  AuthenticatedHojeRoute: AuthenticatedHojeRoute,
  AuthenticatedImportarRoute: AuthenticatedImportarRoute,
  AuthenticatedIntegracaoArenaRoute: AuthenticatedIntegracaoArenaRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedPainelAdmRoute: AuthenticatedPainelAdmRoute,
  AuthenticatedPerdidosRoute: AuthenticatedPerdidosRoute,
  AuthenticatedPlacarDiarioRoute: AuthenticatedPlacarDiarioRoute,
  AuthenticatedProcessosComerciaisRoute: AuthenticatedProcessosComerciaisRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedResgatesRoute: AuthenticatedResgatesRoute,
  AuthenticatedTarefasRoute: AuthenticatedTarefasRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
